[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "goldfish"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.1",
    "PyYAML>=6.0.3",
    "pytest>=9.1.1",
    "torch==2.6.0",
    "tqdm>=4.69.1",
]

[project.scripts]
goldfish = "goldfish.cli:main"
gf = "goldfish.cli:main"

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true
